package com.efreight.base.module.one.record.neone.enums;

/**
 * @author fu yuan hui
 * @since 2024-09-11 13:48:37 星期三
 */
public enum NotifyEventType {

    LOGISTICS_OBJECT_CREATED,

    LOGISTICS_OBJECT_UPDATED,

    /**
     * 拓展的
     */
    LOGISTICS_EVENT_CREATED,

    LOGISTICS_EVENT_RECEIVED,

    // 专用于1号货站与海航对接
    LOGISTICS_EVENT_RECEIVED_MU,

    CHANGE_REQUEST_PENDING,

    CHANGE_REQUEST_ACCEPTED,

    CHANGE_REQUEST_REJECTED,

    CHANGE_REQUEST_FAILED,

    CHANGE_REQUEST_REVOKED,

    ACCESS_DELEGATION_REQUEST_PENDING,

    ACCESS_DELEGATION_REQUEST_ACCEPTED,

    ACCESS_DELEGATION_REQUEST_REJECTED,

    ACCESS_DELEGATION_REQUEST_FAILED,

    ACCESS_DELEGATION_REQUEST_REVOKED,

    SUBSCRIPTION_REQUEST_PENDING,

    SUBSCRIPTION_REQUEST_ACCEPTED,

    SUBSCRIPTION_REQUEST_REJECTED,

    SUBSCRIPTION_REQUEST_FAILED,

    SUBSCRIPTION_REQUEST_REVOKED,

    ;
}
